controllers/AuthController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;
use app\models\LoginForm;
use app\models\SignupForm;

class AuthController extends Controller {
	
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup() {
    	$signupForm = new SignupForm;
    	if (Yii::$app->request->isPost) {
    		$signupForm->load(Yii::$app->request->post());
    		if ($signupForm->signup()) {
                Yii::$app->session->setFlash('success', 'Check your email to finish your registration.');
                return $this->redirect(['site/index']);
            }		
    	}
    	return $this->render('signup', compact('signupForm'));
    }

    public function actionSignupConfirm($token) {
        if (empty($token)) {
            throw new \DomainException('Empty confirm token.');
        }

        $user = User::findOne(['email_confirm_token' => $token]);
        if (!$user) {
            throw new \DomainException('User is not found.');
        }
        $user->email_confirm_token = null;
        $user->save(false);

        if (!Yii::$app->getUser()->login($user)){
            throw new \RuntimeException('Error authentication.');
        }

        Yii::$app->session->setFlash('success', 'You have successfully confirmed your registration.');
        return $this->goHome();
    }
}

views/layouts/admin.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
    <?php $this->beginBody() ?>
        <!--Header with navbar and logo-->
        <nav class="navbar navbar-expand-sm mb-4 navbar-light border bg-light">
            <a href="#" class="navbar-brand">
                My Blog
            </a>
            <button class="navbar-toggler">
                <span class="navbar-toggler-icon" data-toggle="collapse" data-target="#navbar-menu"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item pr-md-2 active">
                        <a href="<?=Url::base(true)?>/site" class="nav-link">Home</a>
                    </li>
                    <?php if (Yii::$app->user->can('admin')):?>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::base(true)?>/admin/user" class="nav-link">Users</a>
                        </li>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::base(true)?>/admin/article" class="nav-link">Articles</a>
                        </li>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::base(true)?>/admin/comment" class="nav-link">Comments</a>
                        </li>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::base(true)?>/admin/category" class="nav-link">Categories</a>
                        </li>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::base(true)?>/admin/tag" class="nav-link">Tags</a>
                        </li>
                    <?php endif;?>
                </ul>
            </div>
        </nav>
        <div class="container-fluid wrapper">
            <?= $content ?>
        </div>
        <!--Footer-->
        <footer class="container-fluid bg-secondary">
            <div class="row py-1 align-items-center justify-content-between text-center">
                <div class="col-sm-6 col-md-3">&copy; MyBlog.com</div>
                <a href="tel:#" class="col-sm-6 col-md-3">Tel: 000-000-000</a>
                <a href="mailto:#" class="col-sm-6 col-md-3">
                    E-mail: example@somemail.com
                </a>
                <div class="col-sm-6 col-md-2">
                    <a href="#">
                        <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-vk fa-2x" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </footer>

        <!--Content: Posts with pagination-->

        <!--Page: Post -> Full text with tags and comments-->

        <!--Page: Register ant Authentification-->

        <!--CMS-->
        
    <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
    <?php $this->beginBody() ?>
        <!--Header with navbar and logo-->
        <nav class="navbar navbar-expand-sm mb-4 navbar-light border bg-light">
            <a href="<?=Url::toRoute(['site/index'])?>" class="navbar-brand">
                My Blog
            </a>
            <button class="navbar-toggler">
                <span class="navbar-toggler-icon" data-toggle="collapse" data-target="#navbar-menu"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item pr-md-2 active">
                        <a href="<?=Url::toRoute(['site/index'])?>" class="nav-link">Home</a>
                    </li>
                    <?php if (Yii::$app->user->can('admin')):?>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::toRoute(['admin/default/index'])?>" class="nav-link">Admin</a>
                        </li>
                    <?php endif;?>
                    <?php if (Yii::$app->user->isGuest):?>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::toRoute(['auth/login'])?>" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item pr-md-2">
                            <a href="<?=Url::toRoute(['auth/signup'])?>" class="nav-link">Register</a>
                        </li>
                    <?php else:?>
                        <li>
                            <a href="<?=Url::toRoute(['/admin/user/view', 'id' => Yii::$app->user->id])?>" class="nav-link">
                                <?='My Profile ('.Yii::$app->user->identity->name.')'?>
                            </a>
                        </li>
                        <li>
                            <a href="<?=Url::toRoute(['/auth/logout'])?>" class="nav-link">
                                Logout
                            </a>
                        </li>
                    <?php endif;?>
                    <li class="nav-item pr-md-2">
                        <a href="<?=Url::toRoute(['site/about'])?>" class="nav-link">About</a>
                    </li>
                    <li class="nav-item pr-md-2">
                        <?=$this->render('/site/partials/search_form')?>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluid wrapper">
            <?= $content ?>
        </div>
        <!--Footer-->
        <footer class="container-fluid bg-secondary">
            <div class="row py-1 align-items-center justify-content-between text-center">
                <div class="col-sm-6 col-md-3">&copy; MyBlog.com</div>
                <a href="tel:#" class="col-sm-6 col-md-3">Tel: 000-000-000</a>
                <a href="mailto:#" class="col-sm-6 col-md-3">
                    E-mail: example@somemail.com
                </a>
                <div class="col-sm-6 col-md-2">
                    <a href="#">
                        <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-vk fa-2x" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </footer>

        <!--Content: Posts with pagination-->

        <!--Page: Post -> Full text with tags and comments-->

        <!--Page: Register ant Authentification-->

        <!--CMS-->
        
    <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main_BAK.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>