controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\Article;
use app\models\Category;
use app\models\Comment;
use app\models\Tag;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SiteSearch;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class SiteController extends Controller {

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout() {
        return $this->render('about');
    }

    public function actionView($id = NULL) {
        $commentModel = new Comment;
        $tags = Tag::getAll();
        $categories = Category::getAll();
        $popularPosts = Article::getPopularPosts();
        $recentPosts = Article::getRecentPosts();
        $currentArticle = Article::find()
            ->with('author', 'tags')
            ->where(['id' => $id])->one();
        $currentArticle->updateCounters(['viewed' => 1]);
        $commentsData = Comment::getAllForThisArticle(
            $currentArticle->id, 4);
        $comments = $commentsData['comments'];
        $pagination = $commentsData['pagination'];
        return $this->render('single_post', compact(
            'comments', 'currentArticle','popularPosts',
            'pagination', 'recentPosts', 'categories',
            'tags', 'commentModel')
        );
    }

    public function actionComment($id) {
        $commentModel = new Comment($id);
        if ($commentModel->load(Yii::$app->request->post())
            && $commentModel->save()) {
            Yii::$app->session->setFlash('comment', 'Your comment was sent to server. It will appear here soon.');
            $this->redirect(['site/view', 'id' => $id]);
        }
    }

    public function actionCategory($id = NULL) {
        $tags = Tag::getAll();
        $popularPosts = Article::getPopularPosts();
        $recentPosts = Article::getRecentPosts();
        $categories = Category::getAll();
        $data = Category::getArticlesByCategory($id);
        $articles = $data['articles'];
        $pagination = $data['pagination'];

        return $this->render('index', compact('articles',
            'popularPosts', 'recentPosts', 'categories', 'tags', 'pagination'));
    }

    public function actionTag($id = NULL) {
        $tags = Tag::getAll();
        $popularPosts = Article::getPopularPosts();
        $recentPosts = Article::getRecentPosts();
        $categories = Category::getAll();
        $data = Tag::getArticlesByTag($id);
        $articles = $data['articles'];
        $pagination = $data['pagination'];

        return $this->render('index', compact('articles',
            'popularPosts', 'recentPosts', 'categories',
                'tags', 'pagination'));
    }

    public function actionSearch($searchQuery) {
        $data = SiteSearch::search($searchQuery);
        $foundArticles = $data['articles'];
        $foundUsers = $data['users'];
        $foundComments = $data['comments'];

        return $this->render('search', compact(
            'foundArticles', 'foundUsers', 'foundComments'));
    }
    
    public function actionIndex() {
        $data = Article::getAll();
        $articles = $data['articles'];
        $pagination = $data['pagination'];
        $tags = Tag::getAll();
        $popularPosts = Article::getPopularPosts();
        $recentPosts = Article::getRecentPosts();
        $categories = Category::getAll();
        
        return $this->render('index', compact('articles',
            'pagination', 'popularPosts', 'recentPosts', 'tags', 'categories'));
    }
}

views/site/partials/comment_form.php
<!--Comment Form-->
<?php
	use yii\helpers\Html;
	use yii\bootstrap\ActiveForm;

	if (!Yii::$app->user->isGuest) {
		$form = ActiveForm::begin([
  		'id' => 'comment-form',
  		'action' => [
  			'site/comment',
  			'id' => $currentArticle->id
  		],
  		'options' => [
  			'class' => 'form-horizontal col-md-8 col-sm-12'
  		]
  	]);

  	echo $form->field($commentModel, 'text')
  		->textArea(['
  			placeholder' => 'Comment text...',
  			'rows' => 3,
  			'cols' => 6
  		])
  		->label('Leave your comment');

		echo Html::submitButton('Leave comment',
			['class' => 'btn btn-primary']);

  	ActiveForm::end();
	}
?>

<?php if (Yii::$app->session->hasFlash('comment')):?>
	<div class="alert alert-success alert-dismissible col-12 mt-2" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo Yii::$app->session->getFlash('comment'); ?>
	</div>
<?php endif;?>

views/site/partials/search_form.php
<!--Search form-->
<form action="/site/search" method="get">
	<div class="input-group">
	  <input type="text" name="searchQuery" class="form-control" placeholder="search..." aria-label="search" aria-describedby="button-addon">
	  <div class="input-group-append">
	    <button class="btn btn-outline-secondary" type="submit" id="button-addon">
	    	<i class="fa fa-search" aria-hidden="true"></i>
	    </button>
	  </div>
	</div>
</form>

views/site/partials/sidebar.php
<?php
    use yii\helpers\Url;
    use yii\helpers\StringHelper;
    use yii\helpers\Html;
?>
<!--Sidebar (popular, recent, categories list)-->
<div class="col-lg-4 col-md-5 sidebar">
    <!--Poular-->
    <div class="list-group popular mb-4">
        <h4 class="list-group-item bg-light">
            <i class="fa fa-star-o" aria-hidden="true"></i>
            <span>Popular posts</span>
        </h4>
        <?php foreach ($popularPosts as $popularPost):?>
            <a href="<?=Url::toRoute(['site/view', 'id' => $popularPost->id])?>" class="list-group-item list-group-item-action">
                <h5 class="d-flex justify-content-between">
                    <span>
                        <?=StringHelper::truncate($popularPost->title, 14)?>
                    </span>
                    <small>
                        <i class="fa fa-eye"></i>
                        <?=$popularPost->viewed?>
                    </small>
                </h5>
                <p class="mb-1">
                    <?=StringHelper::truncate($popularPost->content, 100)?>
                </p>
                <small><?=($popularPost->author) ? Html::encode($popularPost->author->name) : 'Unknown'?></small>
            </a>
        <?php endforeach;?>
    </div>
    <!--Recent-->
    <div class="list-group recent mb-4">
        <h4 class="list-group-item bg-light">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            <span>Recent posts</span>
        </h4>
        <?php foreach ($recentPosts as $recentPost):?>
            <a href="<?=Url::toRoute(['site/view', 'id' => $recentPost->id])?>" class="list-group-item list-group-item-action">
                <div class="d-flex justify-content-between">
                  <h5>
                    <?=StringHelper::truncate($recentPost->title, 14)?>
                  </h5>
                  <small><?=$recentPost->getDate()?></small>
                </div>
                <p class="mb-1">
                    <?=StringHelper::truncate($recentPost->content, 100)?>
                </p>
                <small><?=($recentPost->author) ? Html::encode($recentPost->author->name) : 'Unknown'?></small>
            </a>
        <?php endforeach;?>
    </div>
    <!--Categories-->
    <div class="list-group categories mb-4">
        <h4 class="list-group-item bg-light">
            <i class="fa fa-sticky-note-o" aria-hidden="true"></i>
            <span>Categories</span>
        </h4>
        <?php foreach ($categories as $category):?>
            <a href="<?=Url::toRoute(['site/category', 'id' => $category->id])?>" class="list-group-item list-group-item-action">
                <h5 class="d-flex justify-content-between">
                  <span>
                    <i class="fa fa-circle-thin" aria-hidden="true"></i>
                    <span><?=Html::encode($category->title)?></span>
                  </span>
                  <span class="badge badge-primary badge-pill">
                      <?=$category->getArticlesCount()?>
                  </span>
                </h5>
            </a>
        <?php endforeach;?>
    </div>
    <!--Tags-->
    <div class="list-group categories mb-4">
        <h4 class="list-group-item bg-light">
            <i class="fa fa-tags" aria-hidden="true"></i>
            <span>Tags</span>
        </h4>
        <?php foreach ($tags as $tag):?>
            <a href="<?=Url::toRoute(['site/tag', 'id' => $tag->id])?>" class="list-group-item list-group-item-action">
                <h5 class="d-flex justify-content-between">
                  <span><?=Html::encode($tag->title)?></span>
                  <span class="badge badge-primary badge-pill">
                      <?=count($tag->articles)?>
                  </span>
                </h5>
            </a>
        <?php endforeach;?>
    </div>
</div>